import type { Metadata } from "next";
import { Sora } from "next/font/google";
import "./globals.css";
import NavBar from "./components/NavBar";

const sora = Sora({
  variable: "--font-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${sora.variable} font-sans antialiased`}
      >
        <NavBar />
        {children}
      </body>
    </html>
  );
}
